import type { Verdict } from '@mailtrack/shared';
import { classifyEvent } from '../classifier/rules';
import { CLASSIFIER_SCENARIOS, type ClassifierScenario } from './scenarios';

/**
 * Accuracy measurement harness (PLAN.md ADR-23). Runs the real classifier
 * over the labeled ground-truth corpus and computes a confusion matrix and
 * accuracy figure. Pure — no fs/network here, so it's unit-testable; the
 * report is written to disk by the test that calls formatReport().
 *
 * The number this produces is the classifier's accuracy AGAINST THE LABELED
 * SET (`scenarios.ts`) — it is honest precisely because it is measured, not
 * assumed, and it is bounded precisely because the corpus is finite and
 * hand-labeled. It measures the classifier LOGIC against known real-world
 * patterns; it does NOT prove those patterns match every live client (that's
 * the separate, human-required real-world matrix — see docs/ACCURACY.md).
 */

export interface ScenarioResult {
  scenario: ClassifierScenario;
  actual: Verdict;
  correct: boolean;
}

export interface HarnessReport {
  results: ScenarioResult[];
  total: number;
  correct: number;
  accuracy: number; // 0..1
  /** confusion[expected][actual] = count */
  confusion: Record<Verdict, Record<Verdict, number>>;
  /** per-verdict precision/recall over the corpus */
  perVerdict: Record<Verdict, { precision: number | null; recall: number | null; support: number }>;
}

const ALL_VERDICTS: Verdict[] = ['verified_open', 'verified_click', 'machine_suspect', 'not_verifiable'];

function emptyConfusion(): Record<Verdict, Record<Verdict, number>> {
  const m = {} as Record<Verdict, Record<Verdict, number>>;
  for (const e of ALL_VERDICTS) {
    m[e] = {} as Record<Verdict, number>;
    for (const a of ALL_VERDICTS) m[e][a] = 0;
  }
  return m;
}

export function runHarness(): HarnessReport {
  const results: ScenarioResult[] = CLASSIFIER_SCENARIOS.map((scenario) => {
    const actual = classifyEvent(scenario.input).verdict;
    return { scenario, actual, correct: actual === scenario.expected };
  });

  const confusion = emptyConfusion();
  for (const r of results) confusion[r.scenario.expected][r.actual]++;

  const perVerdict = {} as HarnessReport['perVerdict'];
  for (const v of ALL_VERDICTS) {
    const truePos = confusion[v][v];
    const support = ALL_VERDICTS.reduce((sum, a) => sum + confusion[v][a], 0); // actual instances of v
    const predicted = ALL_VERDICTS.reduce((sum, e) => sum + confusion[e][v], 0); // times v was predicted
    perVerdict[v] = {
      precision: predicted > 0 ? truePos / predicted : null,
      recall: support > 0 ? truePos / support : null,
      support,
    };
  }

  const correct = results.filter((r) => r.correct).length;
  return { results, total: results.length, correct, accuracy: results.length ? correct / results.length : 0, confusion, perVerdict };
}

function pct(x: number | null): string {
  return x === null ? '—' : `${(x * 100).toFixed(1)}%`;
}

/** Renders the report as Markdown. `generatedAtIso` is passed in (not read from the clock) so callers control determinism. */
export function formatReport(report: HarnessReport, generatedAtIso: string): string {
  const lines: string[] = [];
  lines.push('# MailTrack Classifier Accuracy Report');
  lines.push('');
  lines.push('> Auto-generated by `apps/backend/src/accuracy/harness.ts` (PLAN.md ADR-23). Do not edit by hand — run `npm test` in `apps/backend` to regenerate.');
  lines.push('');
  lines.push(`Generated: ${generatedAtIso}`);
  lines.push('');
  lines.push('## Headline');
  lines.push('');
  lines.push(`**Classifier accuracy against the labeled corpus: ${pct(report.accuracy)}** (${report.correct}/${report.total} scenarios).`);
  lines.push('');
  lines.push(
    'This is a measured figure over a hand-labeled set of real-world scenarios (`scenarios.ts`), balanced across cases that MUST verify (real humans) and cases that MUST NOT (Apple MPP, scanners, prefetch, bots). It measures the classifier LOGIC. It does **not** by itself prove those scenarios match every live email client — that requires the real-world client matrix in `docs/accuracy-matrix.md`, which is human-run.',
  );
  lines.push('');
  lines.push('## Per-verdict precision & recall');
  lines.push('');
  lines.push('| Verdict | Precision | Recall | Scenarios |');
  lines.push('|---|---|---|---|');
  for (const v of ALL_VERDICTS) {
    const p = report.perVerdict[v];
    lines.push(`| \`${v}\` | ${pct(p.precision)} | ${pct(p.recall)} | ${p.support} |`);
  }
  lines.push('');
  lines.push('## Confusion matrix (rows = expected, columns = actual)');
  lines.push('');
  lines.push(`| expected ↓ / actual → | ${ALL_VERDICTS.map((v) => `\`${v}\``).join(' | ')} |`);
  lines.push(`|---|${ALL_VERDICTS.map(() => '---').join('|')}|`);
  for (const e of ALL_VERDICTS) {
    lines.push(`| \`${e}\` | ${ALL_VERDICTS.map((a) => String(report.confusion[e][a])).join(' | ')} |`);
  }
  lines.push('');
  const misses = report.results.filter((r) => !r.correct);
  lines.push('## Misclassifications');
  lines.push('');
  if (misses.length === 0) {
    lines.push('None — every labeled scenario was classified correctly.');
  } else {
    for (const m of misses) {
      lines.push(`- **${m.scenario.name}**: expected \`${m.scenario.expected}\`, got \`${m.actual}\` — ${m.scenario.clientContext}`);
    }
  }
  lines.push('');
  lines.push('## Signal reliability (what each dashboard verdict actually means)');
  lines.push('');
  lines.push('| Signal | Reliability | Why |');
  lines.push('|---|---|---|');
  lines.push('| Replied | **Definitive** | A reply must be authored by a human; no sync/proxy/prefetch can produce one (ADR-21). |');
  lines.push('| Clicked | **Very high** | A link navigation, with known link-scanners filtered out. Residual risk: an unlisted corporate scanner. |');
  lines.push('| Read (open+click, or reply) | **Very high** | Two independent signals, plus a proven minimum engaged-time bracket (ADR-18). |');
  lines.push('| Likely read | **High** | At least one verified open — already passed the timing/UA/ASN/burst checks that filter out prefetches and scanners (ADR-29). A genuine human-triggered render, not proof every word was read. |');
  lines.push('| Not verifiable | **N/A (honest abstention)** | Apple MPP / scanner / prefetch detected — we decline to claim a read rather than guess. |');
  lines.push('');
  return lines.join('\n');
}
